# Rancher image
#
# Rancher is an open source project that provides a complete platform for operating Docker in production.
# It provides infrastructure services such as multi-host networking, global and local load balancing, and volume snapshots.
# It integrates native Docker management capabilities such as Docker Machine and Docker Swarm.
# It offers a rich user experience that enables devops admins to operate Docker in production at large scale.
#
# For usage please see the following support files:
#   ./compile_image.sh
#   ./run_image.sh

FROM rancher/server:v1.3.5
MAINTAINER Roger Santos (http://rogeriodossantos.github.io)

# WORKDIR /root/

# RUN mkdir /root/.linux/

# ENTRYPOINT /bin/bash
