# version: '1'

data: 
  image: rogersantos/data
  stdin_open: true
  volumes:
    - ~/.linux:/root/.linux 
    - ~/host:/root/host 

engine:
  image: rogersantos/vim
  stdin_open: true
  volumes_from: 
    - data

