# Docker Registry image
#
# Docker Registry allows you store docker image equivalent to the dockerhub
#
# For usage please see the following support files:
#   ./compile_image.sh
#   ./run_image.sh

FROM registry:2.6.1
MAINTAINER Roger Santos (http://rogeriodossantos.github.io)

# WORKDIR /root/

# RUN mkdir /root/.linux/

# ENTRYPOINT /bin/bash
