# Gluster image
#
# Gluster is a distributed filesystem 
#
# For usage please see the following support files:
#   ./compile_image.sh
#   ./run_image.sh

FROM gluster/gluster-centos:gluster3u9_centos7
MAINTAINER Roger Santos (http://rogeriodossantos.github.io)

# WORKDIR /root/

# RUN mkdir /root/.linux/

# ENTRYPOINT /bin/bash
