# Base Data Image
#
# This image is used by other projects so we can control the versions and features.
#
# For usage please see the following support files:
#   ./compile_image.sh
#   ./run_image.sh

FROM ubuntu:16.04
MAINTAINER Roger Santos (http://rogeriodossantos.github.io)

WORKDIR /root/

RUN mkdir /root/data 

ENTRYPOINT /bin/bash 
