# Raspbian image
#
# Raspbian is the Raspberry Pi official supported operating system. 
#
# For usage please see the following support files:
#   ./compile_image.sh
#   ./run_image.sh

FROM resin/rpi-raspbian:jessie
MAINTAINER Roger Santos (http://rogeriodossantos.github.io)

# WORKDIR /root/

# RUN mkdir /root/.linux/

# ENTRYPOINT /bin/bash
