# Base Portus Image
#
# Portus is a front-end project for docker registry
#
# For usage please see the following support files:
#   ./compile_image.sh
#   ./run_image.sh

FROM opensuse/portus:2.2
MAINTAINER Roger Santos (http://rogeriodossantos.github.io)

# WORKDIR /root/

# RUN apt-get update \
#   && apt-get install -y \
#       tar 

# ENTRYPOINT /bin/bash 
